### ISSUE TITLE
[Discussion] Boolean "reliable" used on function OnMessageReceived

### ISSUE THREAD

**Issue by elton-okawa** [adrenak/airpeer#2]
Hello everyone, how are you?

I've been using Univoice (It's also an amazing project from adrenak 👏) on a Unity personal project , and when I've tested the voice chat room with a friend of mine (outside LAN Network) we've experienced a communication delay of about 3-4 seconds. 
I didn't confirm if it was an internet problem, but I don't think it was.

I was trying to understand the code behind this feature looking for a solution and I reach the following snippet:
https://github.com/adrenak/AirPeer/blob/60d5cf18a64e4ecdba06773c7489ec32ad5960c0/Assets/Adrenak/AirPeer/Scripts/Node.cs#L344-L376

At line 373 it broadcast the message received to the other nodes ignoring the function boolean argument "reliable".
I have 2 questions to discuss:
1. Is it right to ignore the boolean there? In my opinion isn't, because it's not a reserved message so there isn't much problem if we lose it and also, it could be a voice package and then sending it as reliable brings travel delay. There is a high possibility that I'm wrong because I don't fully understand how everything works together.
2. What else could be the origin of my problem?

Thanks!

**Comment by adrenak** [comment]
Hi @elton-okawa , sorry I just saw this issue while cleaning up my mail. I'm familiar with your problem and faced it too.

It's been a while since I worked on this but I remember that the class of `m_Network` that is in a native library didn't honor the reliable flag and the issue of the reliable message queue building up over time continued. The native library is the WebRTC library folder. 

Univoice employs some means to decrease that delay using AudioBuffer and VolumeGate. I'm not sure how clear the code is but the general idea of VolumeGate was to not stream audio when the volume is low for above a threshold amount of time. And AudioBuffer was to construct audio clips from the stream properly.

I would guess that the native library _does_ handle unreliable messages because its creator has made a video call application using it which just cannot operate otherwise. Maybe I wasn't able to use his lib properly or simply made a wrong call in concluding that the unreliable flag was not being honored.

If you have managed to find a solution feel free to make a PR. This issue has held me back from wanting to invest more time in univoice and airpeer which otherwise would be a great solution for many things.

Cheers

**Comment by elton-okawa** [comment]
Hello @adrenak thank you for your answer.

One problem that I addressed was related with Unity Audio Thread. I've noticed that if you have more than one AudioSource playing continually, the AudioSource cannot consume the audio segments as fast as the microphone is generating them, as result, the audio always becomes 1 second delayed (size of the AudioBuffer) and some segments are overwritten because the buffer is full.

I'm still testing out some solutions (it'll take some time because I'm pretty busy with college stuff), but if I find a good solution for this problem, I'll be happy to open a PR for it.

Thanks!

**Comment by adrenak** [comment]
Hi @elton-okawa 

Airpeer and Univoice both have major updates now. As far as the reliable flag goes, I believe that's not the source of the problem.

It seems the delay may have been artificially created in AudioStreamer because of it not being able to handle latency fluctuations. I'm yet to confirm this. The new code does a better job at that, however I'm still testing AudioStreamer (not called InbuiltAudioOutput) to make sure that it indeed is working fine. 

Feel free to check out the new https://www.github.com/adrenak/univoice

**Comment by elton-okawa** [comment]
Hello @adrenak, thank you for your answer

I'll take a look!
